name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm test -- --runInBand --ci --coverage --reporters=default --reporters=jest-junit
      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: junit.xml

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          npm prune --production
          cp node_modules dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
